kind: Deployment
apiVersion: apps/v1
metadata:
  name: myappcontainer
spec:
  selector:
    matchLabels:
      app: myappcontainer
  replicas: 1
template:
  metadata:
    labels:
      app: myappcontainer
      version: v1
  spec:
    containers:
    - name: myappcontainer
      image: myappcontainer:1
  ports:
    - containerPort: 8080
    imagePullPolicy: Never
  restartPolicy: Always