pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'npm install -g npm@7.5.0'
            }
        }
        stage('Test') {
            steps {
				echo "un echo..."
            }
        }
        stage('Deploy') {
            steps {
				dir('main_app-page'){
					bat 'docker build -f Dockerfile -t myappcontainer:1 .'
					bat 'docker run -it myappcontainer:1 bash'
					bat 'kubectl apply -f deployment.yaml'
					bat 'kubectl apply -f service.yaml'
					bat 'minikube dashboard'
				}
            }
        }
    }
}