pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'npm install -g npm@7.5.0'
            }
        }
        stage('Test') {
            steps {
                bat 'cd main_app-page run start'
            }
        }
        stage('Deploy') {
            steps {
				echo 'hola...'
            }
        }
    }
}